apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: habit-tracker
type: Opaque
data:
  # Base64 encoded values
  # echo -n "postgres" | base64
  POSTGRES_USER: cG9zdGdyZXM=
  # echo -n "postgres123" | base64
  POSTGRES_PASSWORD: cG9zdGdyZXMxMjM=
  # echo -n "habit_tracker" | base64
  POSTGRES_DB: aGFiaXRfdHJhY2tlcg==
